parameters:
    admingenerator.doctrine.class: Melody\AdminBundle\Generator\DoctrineGenerator
    twig.loader.filesystem.class: Melody\AdminBundle\Twig\Loader\FilesystemLoader

framework:
    templating:
        packages:
             admingenerator_css:
                version: 1.0
                version_format: "%%1$s?v%%2$s"
             admingenerator_js:
                version: 1.0
                version_format: "%%1$s?v%%2$s"
             formextensions_css:
                version: 1.0
                version_format: "%%1$s?v%%2$s"
             formextensions_js:
                version: 1.0
                version_format: "%%1$s?v%%2$s"

# AdminGenerator Configuration
admingenerator_generator:
    use_propel:       "%orm_propel%"
    use_doctrine_orm: "%orm_doctrine%"
    base_admin_template: MelodyAdminBundle::base.html.twig
    stylesheets:
      - { path: bundles/admin/css/common.css }
    templates_dirs:
        - "%kernel.root_dir%/../vendor/melody/admin/Resources/templates"
        - "%kernel.root_dir%/../vendor/symfony2admingenerator/generator-bundle/Resources/templates"
    form_types:
        doctrine_orm:
            datetime:     s2a_datetime_picker
            vardatetime:  s2a_datetime_picker
            datetimetz:   s2a_datetime_picker
            date:         s2a_datetime_picker
        doctrine_odm:
            datetime:     s2a_datetime_picker
            vardatetime:  s2a_datetime_picker
            datetimetz:   s2a_datetime_picker
            date:         s2a_datetime_picker
        propel:
            TIMESTAMP:    s2a_datetime_picker
            BU_TIMESTAMP: s2a_datetime_picker
    filter_types:
        doctrine_orm:
            datetime:     s2a_daterange_picker
            vardatetime:  s2a_daterange_picker
            datetimetz:   s2a_daterange_picker
            date:         s2a_daterange_picker
        doctrine_odm:
            datetime:     s2a_daterange_picker
            vardatetime:  s2a_daterange_picker
            datetimetz:   s2a_daterange_picker
            date:         s2a_daterange_picker
        propel:
            TIMESTAMP:    s2a_daterange_picker
            BU_TIMESTAMP: s2a_daterange_picker

admingenerator_form_extensions:
    upload_manager:           ~
    image_manipulator:        ~
    twig:
        use_form_resources:     true
    collection_upload:
        async_listener_enabled: false
        async_route_name:       ~
        file_storage:           admingenerator.form.file_storage.local
    # you need these JS assets for some form types
    # if you set it to true, the bundle will include them for you
    # otherwise you have to do it manually
    include_jquery:           true
    include_jqueryui:         true
    include_momentjs:         true
    include_blueimp:          true 
    include_gmaps:            true

# Knp Menu Configuration
knp_menu:
    providers:
        builder_alias: true
        container_aware: true

jms_di_extra:
    locations:
        all_bundles:  true
#        bundles:      []
        directories:  ["%kernel.root_dir%/../src"]

jms_security_extra:
    # Enables expression language
    secure_all_services: false
    expressions: true

# services
services: 
    menu_builder:
        class: Melody\AdminBundle\Menu\Builder
        arguments: ["@knp_menu.factory","@service_container"]
      
    menu.admin:
        class: Knp\Menu\MenuItem
        factory_service: menu_builder
        factory_method: createAdminMenu
        arguments: ["@request"]
        scope: request
        tags:
          - { name: knp_menu.menu, alias: admin }

hwi_oauth:
    firewall_name: account
    connect:
        confirmation: true
    fosub:
        username_iterations: 30